# Use the official PostgreSQL image as a parent image
FROM postgres:latest

# Set the environment variables for PostgreSQL
ENV POSTGRES_DB Wifi_Details
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 123456
